// react/first-app/src/components/recipe/recipe.js
import React from 'react';
import './recipe.css'

import Card from '@material-ui/core/Card';
import CardActions from '@material-ui/core/CardActions';
import CardContent from '@material-ui/core/CardContent';
import Typography from '@material-ui/core/Typography';

function Recipe(props) {

  return (

    <Card class="fade-in example-card">

      <CardContent>

        <Typography class="mat-card-header">
          {props.name}
        </Typography>

        <img class="example-header-image" src={props.picture} />

        <br />
        <p class="bold">Ingredients</p>
        <p>
          {props.description}
        </p>
        <div>
          {props.ingredients.map((ing) =>
            <li >
              {ing.name}
              {ing.quantity}
              {ing.unit}
            </li>)
          }
          <br />
          <p class="bold">Steps</p>
          <ol>
            {props.instructions.map((ins) =>
              <li >
                {ins}
              </li>)
            }
          </ol>
        </div>

      </CardContent>

      <CardActions>
        <button>Show Details</button>
      </CardActions>

    </Card>

  );
}

export default Recipe;

// angular/first-app/src/app/recipe/recipe.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { MOCK_RECIPES } from 'src/assets/recipes.mock';
import { Recipe } from '../model/recipe.model';

@Component({
  selector: 'app-recipe',
  templateUrl: './recipe.component.html',
  styleUrls: ['../app.component.scss','./recipe.component.scss']
})
export class RecipeComponent implements OnInit {
  @Input()
  recipe: Recipe = MOCK_RECIPES[1];
  bool: boolean = false;
  textButton = 'See more';

  constructor() { }

  ngOnInit(): void {

  }

  toggleExpand() {
    this.bool = !this.bool;
    this.bool ? this.textButton = 'See less' : this.textButton = 'See more';
  }

}

<mat-card class="example-card">
    <mat-card-header>
        <div mat-card-avatar class="example-header-image"></div>
        <mat-card-title>{{recipe.name}}</mat-card-title>
    </mat-card-header>
    <img mat-card-image [src]="recipe.picture" alt="recipe.name">
    <mat-card-content>
        <p>
            {{recipe.description}}
        </p>
        <ng-container *ngIf="bool">
            <ul>
                <li *ngFor="let ingredient of recipe.ingredients">
                    {{ingredient.ingredient.name}}
                    {{ingredient.quantity}}
                    {{ingredient.unit}}
                </li>
            </ul>
            <ol>
                <li *ngFor="let instruction of recipe.instructions">
                    {{instruction}}
                </li>
            </ol>
        </ng-container>
    </mat-card-content>
    <mat-card-actions>
        <button (click)=toggleExpand()>
            {{textButton}}
        </button>
        <button routerLink="/recipes/{{recipe.id}}">
            More Details
        </button>
    </mat-card-actions>
</mat-card>
